### PR TITLE
Electron base, transparency, sass

### PR DESCRIPTION
**Pull request by pgaetani**
Initial electron base, got transparent BG, as well as using SASS (as per the stack proposed). Added "buid-css" and "watch-css" scripts to package.json for easier SASS usage.

At the moment, it can be tested by:

- Downloading the branch
- Running *npm install*
- Running *npm run build-css*
- Running *npm start*

### CODE REVIEW

**Comment by pgaetani** [comment]
Do remember to add yourselves to the "contributors" part of the package.json if and when you guys modify things.

**Comment by pgaetani** [comment]
Added a little custom sprite gif (yes, made it myself, no copyright) for better experimentation, also made the canvas full-screen, as we'll probably have to play with positioning within the canvas itself.

**Comment by Chovin** [comment]
image
why are we ignoring this? is it cause it gets rebuilt by sass?

**Comment by pgaetani** [comment]
Yes, precisely because it gets built by sass.

**Comment by pgaetani** [comment]
Prestart task now just runs 'default' task from gulp (generates html/css using pug/sass). Watch tasks added to gulp for both pug and sass files, run `gulp watch` for this, running simply `gulp` regenerates files.

Stack is taking shape, boys.

**Comment by Chovin** [comment]
good electron base and stack to work off of. merging

**Pull request merged**
